name: "Pull request"
on:
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  validation:
    name: "Gradle Wrapper Validation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
  test:
    name: Test run
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        java: [ 11, 17 ]
    needs: validation
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      - name: Make gradlew executable (non-Windows only)
        if: matrix.os != 'windows-latest'
        run: chmod +x ./gradlew
      - name: Gradle Check (non-Windows)
        if: matrix.os != 'windows-latest'
        run: ./gradlew --info check
      - name: Gradle Check (Windows)
        if: matrix.os == 'windows-latest'
        shell: cmd
        run: gradlew --info check
